server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:air;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger (springdoc)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
